### PR TITLE
posts_data: allow proxy address and port configuration

### PR DESCRIPTION
**Pull request by pierre**
Tested using the Kill Bill CyberSource plugin (http://github.com/killbill/killbill-cybersource-plugin).

### CODE REVIEW

**Comment by wvanbergen** [comment]
- Can you rebase on the latest master?
- Can you add a test?

**Comment by wvanbergen** [comment]
@jnormore @kmcphillips thoughts?

**Comment by jnormore** [comment]
I don't see why not, needs tests though :)

**Comment by wvanbergen** [comment]
#59 implemented this!

**Pull request closed without merging**
