### PR TITLE
Remove unused and duplicate method

### PR DESCRIPTION
**Pull request by kenchan**
`Connection#handle_response` is unused.

I think that we should use `PostsData#handle_response`.

### CODE REVIEW

**Comment by wvanbergen** [comment]
@jnormore @kmcphillips can you review this? Should/do we use `PostsData#handle_response`?

**Comment by wvanbergen** [comment]
Note: this will need to be rebased onto the latest master.

**Comment by kmcphillips** [comment]
Could we get a rebase and a test first?

**Comment by wvanbergen** [comment]
Not sure about the test: it just removes code, and apparently that doesn't make any test fail, so I guess that's a good sign!?

**Comment by kenchan** [comment]
rebased.

I have this method was confirmed that not being used in active_merchant and active_utils, test is required?

**Pull request closed without merging**
